# Generated by Django 2.2.6 on 2019-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20191006_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
